### ISSUE TITLE
Error using GDSync.start_multiplayer()

### ISSUE THREAD

**Issue by axilirate** [GD-Sync/GD-Sync#38]
some of my players are constantly getting this error:
`ERROR: No valid connection. Please connect using GDSync.start_multiplayer() first
   at: push_error (core/variant/variant_utility.cpp:1098)
`

and attempting to call `GDSync.start_multiplayer()` results in the same error.
this is consistent.

the connection_failed signal is emitted with error = 1

the solution here doesn't work either
https://github.com/GD-Sync/GD-Sync/issues/2#issue-2253396481

**Comment by ThomasUijlen** [comment]
Hi there,

We are unable to replicate the issue on our end. Could you try again and see if the error still persists?

**Comment by axilirate** [comment]
![Image](https://github.com/user-attachments/assets/2181f96c-1de1-47ca-b3a8-5cad00a052ce)
compared to actually players that are in game

![Image](https://github.com/user-attachments/assets/ab4ede0e-0c32-452a-8a76-85eb197ab6f8)

**Comment by axilirate** [comment]
```
var gd_sync_connection_locked: bool = false

func _ready() -> void:
	process_mode = ProcessMode.PROCESS_MODE_ALWAYS
	
	GDSync.connection_failed.connect(_on_gd_sync_connection_failed)
	GDSync.disconnected.connect(_on_gd_sync_disconnected)
	GDSync.connected.connect(_on_gd_sync_connected)
	
	GDSync.start_multiplayer()


func try_to_reconnect():
	if gd_sync_connection_locked == true:
		gd_sync_connection_locked = false
		await get_tree().create_timer(1).timeout
		GDSync.start_multiplayer()
		return
	
	gd_sync_connection_locked = true
	print("trying to reconnect")
	GDSync.stop_multiplayer()
	try_to_reconnect()



func _on_gd_sync_connection_failed(error : int) -> void:
	print("GD Sync connection failed: ", error)
	try_to_reconnect()


func _on_gd_sync_disconnected() -> void:
	print("GD Sync connection failed")
	try_to_reconnect()


func _on_gd_sync_connected() -> void:
	print("connected to gd sync!")
```

the code

**Comment by ThomasUijlen** [comment]
Hi again,

After further investigation, we identified a server-side issue that may have interfered with connection attempts. As of yesterday, a hotfix has been deployed, and the issue should now be resolved. We will continue monitoring the situation.

We apologize for any impact on your players and any inconvenience caused. Please let us know if the problem persists.

**Comment by axilirate** [comment]
Thanks for the work, but I believe the issue still persists,

I monitor the player count though SteamDB:
https://steamdb.info/app/2440380/

and it doesn't match the player count in the GDSync Dashboard
![Image](https://github.com/user-attachments/assets/bce8096e-4582-4385-9b26-64e85ea2f417)

![Image](https://github.com/user-attachments/assets/4373ef8d-a4ac-4a0a-9ce2-5a589745d952)

**Comment by ThomasUijlen** [comment]
Just to confirm:
- is the code you shared for connecting in autoload? Or is it just a Node inside a scene?
- Do you always establish a connection or only when someone selects multiplayer/co-op?

**Comment by axilirate** [comment]
It's an autoload, and the connection is established immediately.
Also, I think it's getting better player wise.

**Comment by axilirate** [comment]
closing the issue, seems like it's fine now, thanks.

**Comment by axilirate** [comment]
reopening as it seems like it's still not fixed for some players, I'll attach a log file for reference.

![megaloot2025-04-16T12.15.09.log.txt](https://github.com/user-attachments/files/19770438/megaloot2025-04-16T12.15.09.log.txt)

**Comment by K1fu** [comment]
Good day. I am currently facing the same issue while developing the game. 

I have attached the correct private and public key yet I still cannot connect to GDSync.

![Image](https://github.com/user-attachments/assets/2e9b52c1-df17-404a-bd58-ff60044473ec)

**Comment by ThomasUijlen** [comment]
Do you know which region(s) the players that report the issue are from?

**Comment by axilirate** [comment]
I know that one is from Turkey and another is from US- northwest.
Also it seems that after a couple of hours some are able to log again.

**Comment by ThomasUijlen** [comment]
We will continue to investigate the situation. I will update you as soon as I have more information.

**Comment by ThomasUijlen** [comment]
Hi again,

With the server upgrade (#41) to 4.3, we also made improvements to server and connection stability. Players should no longer experience connection related issues. We will continue to monitor the situation closely.

In the meantime, please let me know if players report any issues in the coming days.

**Comment by axilirate** [comment]
Hey, the one player that's unable is still experiencing the issue.
Is the any info I can provide to help?

**Comment by ThomasUijlen** [comment]
My guess is this is probably a player specific issue. Info that would be useful is the following:
- Platform (Windows, Linux, etc)
- Country
- Are they using a VPN?
- Did they ever experience similar issues with other games?
- Are they behind a school/corporate network?


Options they could try to resolve it are:
- Disabling firewall and/or anti-virus to see if that is blocking it.
- Try using a VPN, maybe your country cannot have direct access to any of the servers.
- Try using a different WiFi network to see if the issue is caused by their router or internet provider.

**Comment by axilirate** [comment]
I got no answer from him, I guess since it's player specific, this issue can be closed.

**Comment by axilirate** [comment]
Happens again
